name: CI Pipeline

on:
  push:
    branches: [ main ] # تشغيل هذا السير العمل عند الرفع على فرع main فقط

jobs:
  build-and-push:
    runs-on: ubuntu-latest # استخدام نظام تشغيل Linux للبناء
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # سحب الكود من GitHub
      
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME}}     
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          DOCKER_USERNAME/devops-app:latest
          DOCKER_USERNAME/devops-app:${{ github.sha }}